import { StyleSheet } from "react-native";
import { colors } from "../../../constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  contentContainer: { padding: 16, paddingBottom: 32 },
  header: {
    backgroundColor: colors.cardBackground,
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 16,
    shadowColor: colors.shadow,
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  headerTop: { height: 56, backgroundColor: colors.primary },
  headerContent: { padding: 16, flexDirection: "row", alignItems: "center" },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    marginRight: 16,
    borderWidth: 2,
    borderColor: colors.background,
  },
  avatarPlaceholder: {
    width: 72,
    height: 72,
    borderRadius: 36,
    marginRight: 16,
    backgroundColor: colors.navActive,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitials: { fontSize: 28, fontWeight: "700", color: colors.primary },
  headerInfo: { flex: 1 },
  topRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  name: {
    fontSize: 24,
    fontWeight: "bold",
    color: colors.primaryText,
    marginBottom: 6,
  },
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 8,
    marginTop: 2,
  },
  metaChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
  },
  metaText: {
    marginLeft: 6,
    fontSize: 12,
    color: colors.primaryText,
    fontWeight: "500",
  },
  statusChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: colors.navActive,
    borderRadius: 999,
  },
  statusText: {
    fontSize: 12,
    color: colors.primary,
    fontWeight: "600",
    marginLeft: 6,
  },
  badgesRow: { flexDirection: "row", gap: 8 },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
  },
  badgeText: {
    marginLeft: 6,
    fontSize: 12,
    color: colors.primaryText,
    fontWeight: "500",
  },
  card: {
    backgroundColor: colors.cardBackground,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: colors.shadow,
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
    overflow: "visible",
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.primaryText,
    marginBottom: 12,
  },
  cardHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  itemRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  itemContent: { marginLeft: 12, flex: 1 },
  itemLabel: { fontSize: 12, color: colors.secondaryText, marginBottom: 2 },
  itemValue: { fontSize: 16, color: colors.primaryText },
  iconBadge: {
    width: 36,
    height: 36,
    borderRadius: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  editChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.background,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
  },
  editChipText: {
    marginLeft: 6,
    fontSize: 12,
    color: colors.primary,
    fontWeight: "600",
  },
  editActionsRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  editChipPrimary: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  editChipTextPrimary: {
    marginLeft: 6,
    fontSize: 12,
    color: colors.whiteText,
    fontWeight: "700",
  },
  formGroup: { marginBottom: 12 },
  formLabel: { fontSize: 12, color: colors.secondaryText, marginBottom: 6 },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: colors.primaryText,
    backgroundColor: colors.backgroundLight,
  },
  actionsRow: { flexDirection: "row", gap: 12, marginBottom: 16 },
  actionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: colors.buttonLight,
    borderWidth: 1,
    borderColor: colors.border,
  },
  actionPrimary: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  actionLabel: { fontSize: 14, color: colors.primary, fontWeight: "600" },
  actionLabelPrimary: {
    fontSize: 14,
    color: colors.whiteText,
    fontWeight: "700",
  },
  errorText: {
    fontSize: 16,
    color: colors.error,
    textAlign: "center",
    marginTop: 50,
  },
  ctaCard: {
    marginBottom: 16,
    backgroundColor: colors.cardBackground,
    borderRadius: 12,
    padding: 14,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.shadow,
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 1,
    width: "100%",
  },
  ctaIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: colors.navActive,
    alignItems: "center",
    justifyContent: "center",
  },
  ctaTextWrap: { flex: 1 },
  ctaTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.primaryText,
    marginBottom: 2,
  },
  ctaSubtitle: { fontSize: 12, color: colors.secondaryText },
});
